### ISSUE TITLE
Force upload don't seem to work anymore

### ISSUE THREAD

**Issue by Fogh** [mbogh/fastlane-plugin-tpa#11]
So when you force upload an app with the same version number as one that already exists on TPA, then the app don't seem to be replace by the new one.

It seems that something has changed on the TPA side.

**Comment by mbogh** [comment]
It works from the GUI with the same ipa/dsym...

**Comment by mbogh** [comment]
TPA says the force upload does indeed work but a bug caused the timestamp to not be updated.
They will fix it as soon as possible.

**Comment by mbogh** [comment]
Lets close it for now
